
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mojabazadanych
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:
